---
name: Build-NFR
on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - app/**
  pull_request:
    branches:
      - main
    paths:
      - app/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10.3-2021.07'
          
      - name: Build NFR source
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output Binaries
          path: ./app/pca10040/s132/armgcc/_build

